### ISSUE TITLE
Show something else

### ISSUE THREAD

**Issue by tgrignon** [clarkwinkelmann/flarum-ext-email-as-display-name#10]
This is not an issue, more like a request.

In Flarum I want specific users displayed with full name, they are administrators or employee. They subscribe to Flarum with a dirty username, but want users knows who they are. So I modified the script to verify if the specific user have a BIO and use this as display name. I use the bio variable in table users for that.

If you can include an option in a next version of your extension.

UserAttributes.php

```
            if (!$user->bio) $temp = $user->username;
            else $temp = $user->bio;
            
            return [
                'displayName' => $temp,
            ];
```

**Comment by clarkwinkelmann** [comment]
This seems out of scope for this extension. This extension is about showing email, your suggestion switches between username and bio. That would require a adding new options in the admin panel to accommodate all combinations. IMO it's better as a separate extension, so that no additional settings are required, just enable the desired extension.

It sounds like your use case could be met by the bundled Nickname extension. You can customize which groups are able to set a Nickname for themselves.

Also, it's not merged yet, but your code might break once TextFormatter support is introduced into FoF Bio in the near future https://github.com/FriendsOfFlarum/user-bio/pull/42 I'm not sure whether datitisev accounted for backward compatibility in the PHP code.
